### ISSUE TITLE
Using Escrow?

### ISSUE THREAD

**Issue by ghost** [orangerdev/jobster-midtrans#1]
Apakah bisa split payment gitu?, misalnya nanti admin dapat 10% dari transaksi yang terjadi.

**Comment by orangerdev** [comment]
kalau langsung ketika transaksi, tidak ada fitur tersebut.

paling buat saja tercatat di sistem dan nanti dibayarkannya manual

**Comment by ghost** [comment]
Oh jadi begitu, thanks ya mas

**Comment by orangerdev** [comment]
setahu saya untuk pembayaran model tersebut belum ada di payment gateway indonesia / bank-bank indonesia, 

adanya di paypal, namanya adaptive payment

**Comment by ghost** [comment]
ada mas satu payment gateway yang bisa yaitu https://ipaymu.com/ terus ada sistem escrow nya juga https://ipaymu.com/escrow/

**Comment by orangerdev** [comment]
oh iya, ok ok, baru baca ini
